### PR TITLE
Method to add link for facet search on a field

### LINKED ISSUE #1586: link_to_search config not working
Class year is supposed to be clickable as a facet: https://catalog.princeton.edu/catalog/dsp01zk51vk08g
https://github.com/pulibrary/orangelight/blob/master/app/controllers/catalog_controller.rb#L175

### PR DESCRIPTION
**Pull request by christinach**
closes #1586

### CODE REVIEW

File: app/controllers/catalog_controller.rb [hunk 1]
```diff
@@ -294,7 +295,7 @@ class CatalogController < ApplicationController
     config.add_show_field 'recap_notes_display', label: 'RCP', helper_method: :recap_note
 
     # Numismatics fields
-    config.add_show_field 'issue_number_s', label: 'Issue', link_to_search: true, if: false
+    config.add_show_field 'issue_number_s', label: 'Issue', helper_method: :link_to_search_value
```
Comment (tampakis) [inline app/controllers/catalog_controller.rb]: keep the `if: false` so that the issue number can appear at the top of the page

Comment (christinach) [reply app/controllers/catalog_controller.rb]: nice @tampakis , thanks you. i didn't know this blacklight magic.

Comment (tampakis) [reply app/controllers/catalog_controller.rb]: Orangelight magic, but magic nonetheless

File: app/helpers/application_helper.rb [hunk 2]
```diff
@@ -307,6 +307,15 @@ def name_title(args)
     end
   end
 
+  def link_to_search_value(args)
+    if args[:document][args[:field]].present?
```
Comment (tampakis) [inline app/helpers/application_helper.rb]: this line isn't needed, blacklight checks to make sure the field is present before running the method

File: app/helpers/application_helper.rb [hunk 3]
```diff
@@ -307,6 +307,15 @@ def name_title(args)
...
+      args[:document][args[:field]].each_with_index do |field_t, i|
```
Comment (tampakis) [inline app/helpers/application_helper.rb]: the variable name `field_t` is misleading. `field` is consistent with the other methods

File: app/helpers/application_helper.rb [hunk 4]
```diff
@@ -307,6 +307,15 @@ def name_title(args)
...
+        field_link = link_to(field_t, "/?f[#{args[:field]}][]=#{CGI.escape field_t}", class: 'search-name', 'data-toggle' => 'tooltip', 'data-original-title' => "Search: #{field_t}", title: "Search: #{field_t}")
+        args[:document][args[:field]][i] = field_link.html_safe if field_link
```
Comment (tampakis) [inline app/helpers/application_helper.rb]: the `if field_link` check isn't necessary. Neither is the `html_safe` because the `link_to` method returns an html-safe string (and allows the link html to render correctly)

File: app/helpers/application_helper.rb (hunk 2 above)
Comment (christinach) [reply app/helpers/application_helper.rb]: I'll update this one but I don't know where this check is done.

**Comment by tampakis** [comment]
Thanks @christinach !
