### PR TITLE
Handle facets with nil values

### LINKED ISSUE #1414: [Orangelight/production] ActionView::Template::Error: undefined method `collect' for nil:NilClass
## Backtrace

    line 3 of [PROJECT_ROOT]/app/views/advanced/_advanced_search_form.html.erb: block in _app_views_advanced__advanced_search_form_html_erb__3271812339700670366_70163712473180
    line 1 of [PROJECT_ROOT]/app/views/advanced/_advanced_search_form.html.erb: _app_views_advanced__advanced_search_form_html_erb__3271812339700670366_70163712473180
    line 10 of [PROJECT_ROOT]/app/views/advanced/index.html.erb: _app_views_advanced_index_html_erb___2579382378759579142_70163712561680

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/39817745)

Offending query:

```
GET https://catalog.princeton.edu/advanced?%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2Bf%5Bformat%5D%5B%5D=musical%2Bscore&%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2Bf%255bformat%255d%255b%255d=book&%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2Bf%5Baccess_facet%5D%5B%5D=online&%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2Bf%5Brecently_added_facet%5D%5B%5D=months_2&%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2Bf%5Brecently_added_facet%5D%5B%5D=months_2&%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2Bf%5Blocation%5D%5B%5D=architecture%2Blibrary&%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2B%2Bf%5Blocation%5D%5B%5D=recap&%2B%2B%2B%2B%2B%2B%2B%2Bf%5Blocation%5D%5B%5D=east%2Basian%2Blibrary&%2B%2B%2B%2Bf%255bsubject_facet%255d%255b%255d=missionaries%25e2%2580%2594china%25e2%2580%2594biography&%2B%2B%2B%2Bf%5Bformat%5D%5B%5D=visual%2Bmaterial&f%5Bformat%5D%5B
```

### PR DESCRIPTION
**Pull request by eliotjordan**
Adds facets with nil value to list of invalid parameter handler.

Closes #1414

### CODE REVIEW

File: lib/orangelight/middleware/invalid_parameter_handler.rb [hunk 1]
```diff
@@ -46,24 +50,43 @@ def default_content_type
...
 
-        def bad_request_response
+        def request_content_type(env)
+          request = request_for(env)
+          request.formats.first || default_content_type
+        end
+
+        def request_for(env)
+          # calling env.dup here prevents bad things from happening
+          ActionDispatch::Request.new(env.dup)
```
Comment (eliotjordan) [inline lib/orangelight/middleware/invalid_parameter_handler.rb]: Caching the request was causing problems because that cached value persists between calls. Unfortunately, this adds some complexity to the methods because we have to pass the `env` variable around more than before.

**Comment by eliotjordan** [comment]
@jrgriffiniii What do you think about this? I'm open to suggestions and commits. This was supposed to be a 30 minute Honeybadger investigation that turned into an afternoon. 😜
