### PR TITLE
Avoid constraint display error when facets applied in certain order

### LINKED ISSUE #2874: Advanced Search fails when right hand side choices are added to an existing search (has facets)
ActionView::Template::Error: undefined method `to_sym' for ["Mendel Music Library", "ReCAP"]:Array
Did you mean?  to_s
               to_set

honeybadger error:
https://app.honeybadger.io/projects/54399/faults/84204121

https://github.com/pulibrary/orangelight/blob/652a275746d36b11f07b10d044259268d97fc2eb/app/helpers/application_helper.rb#L392

def render_location_code(value)
  location = Bibdata.holding_locations[value.to_sym]
  ocation.nil? ? value : "#{value}: #{location_full_display(location)}"
end

### PR DESCRIPTION
**Pull request by sandbergja**
closes #2874 

Here is an easy way to trigger this issue on production:
1. Go to [the production catalog](https://catalog.princeton.edu/)
2. Select a Format Facet
3. Push Edit Search button
4. Select one or many holding locations
5. Push search button

Without the fix, you will get "We're sorry, but there was a problem processing the page you requested."  With the fix, you will at least get results, just with goofy-looking duplicative constraints view.

### CODE REVIEW

File: app/helpers/application_helper.rb [hunk 1]
```diff
@@ -389,8 +389,12 @@ def bibdata_location_code_to_sym(value)
   end
 
   def render_location_code(value)
-    location = Bibdata.holding_locations[value.to_sym]
-    location.nil? ? value : "#{value}: #{location_full_display(location)}"
+    if value.is_a?(Array)
+      value.map { |v| render_location_code(v) }
```
Comment (carolyncole) [inline app/helpers/application_helper.rb:393]: @sandbergja Recursion is a bit complex in this situation.  I might have just cast the single value to an Array with 
```
Array(value).map do |loc|
   location = Bibdata.holding_locations[loc.to_sym]
   location.nil? ? value : "#{value}: #{location_full_display(location)}"
end
```

File: spec/system/searching_spec.rb [hunk 2]
```diff
@@ -121,4 +121,9 @@
     visit "/catalog?f[subject_facet][]=Japan%E2%80%94History"
     expect(page).to have_content '1 entry found'
   end
+
```
Comment (carolyncole) [inline spec/system/searching_spec.rb:124]: This test is great.  There is also a test for the helper, which would be a great place to add a test for the syntax of the output https://github.com/pulibrary/orangelight/blob/34bf790fd5fb9aab0cdbbd7f514ff0b5d2c39fa4/spec/helpers/locations_spec.rb#L49

**Review by carolyncole — CHANGES_REQUESTED** [review]
Nice work tracking down a quick fix.  I had a couple comments on the changes.  If making these updates does not make sense because this is not the final code just let me know.

**Review by carolyncole — APPROVED** [review]

**Review by christinach — APPROVED** [review]
