### PR TITLE
Manage bad data with empty enum and description. Remove unused Preservation conservation check

### LINKED ISSUE #5755: Items with bad data (enum or description empty strings) should not prevent from sending to illiad if the rest of the checks satisfy the criteria
### What maintenance needs to be done?
The specific issue appears for items in East Asian with bad data in Alma that fail the eligibility check for the Illiad service. 
The problem was only revealed now after the changes in https://github.com/pulibrary/bibdata/pull/3178. 

For the East Asian items the enum and description values are empty strings, so the specific  method returns that are present and not nil . The next Illiad eligibility check is the Preservation Conservation which does not exist anymore as a status label. So the Illiad service eligibility check fails.

### Level of urgency
- [x] High
- [ ] Moderate
- [ ] Low

### Why is this maintenance needed?
- Patrons cannot request through Illiad an item tht is in Preservation Conservation.

### 
Example:
https://catalog.princeton.edu/requests/9942430233506421?aeon=false&mfhd=22600149340006421&open_holdings=East+Asian+Library

This issue is related to bad data in Alma and exists in the catalog production for years.

### PR DESCRIPTION
**Pull request by christinach**
closes #5755

Make sure description and enum is not an empty string

The specific issue appears for items in East Asian with bad data in Alma that fail the eligibility check for the Illiad service. The problem was only revealed now after the changes in https://github.com/pulibrary/bibdata/pull/3178.

For the East Asian items the enum and description values are empty strings, so the specific  method returns that are present and not nil . The next Illiad eligibility check is the Preservation Conservation which does not exist anymore as a status label. So the Illiad service eligibility check fails.

related to [#5755]

### CODE REVIEW

File: app/models/requests/item.rb [hunk 1]
```diff
@@ -54,10 +54,6 @@ def on_reserve?
       self[:on_reserve] == 'Y'
     end
 
-    def preservation_conservation?
-      status_label == "Preservation and Conservation"
```
Comment (christinach) [inline app/models/requests/item.rb:58]: In bibdata we're setting status label Unavailable when the work order type is Preservation and Conservation.

File: app/models/requests/item.rb [hunk 2]
```diff
@@ -128,11 +124,13 @@ def location
     private
 
       def short_description_from_alma_availability_call
-        self[:enum_display]
```
Comment (christinach) [inline app/models/requests/item.rb:131]: East Asian items appear to have empty strings for enum and description.

Comment (kevinreiss) [reply app/models/requests/item.rb:131]: Interesting, I wonder why they have a different cataloging practice for this data.

**Review by kevinreiss — APPROVED** [review]
Thanks @christinach
