### PR TITLE
Provides redirection for cases where clients attempt to query advanced#index with catalog queries

### LINKED ISSUE #1336: Research how to trigger invalid "back to search" link
## Backtrace

    line 39 of [PROJECT_ROOT]/config/initializers/blacklight_url_helper_behavior.rb: link_back_to_catalog
    line 9 of [PROJECT_ROOT]/app/views/catalog/_previous_next_doc.html.erb: _app_views_catalog__previous_next_doc_html_erb___141562302411537421_70097437451980
    line 1 of [PROJECT_ROOT]/app/views/catalog/show.html.erb: _app_views_catalog_show_html_erb__621661626053428788_36727780

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/36655673)

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #1336 by ensuring that catalog query parameters in requests for the advanced search index trigger a redirect response

### CODE REVIEW

File: app/controllers/advanced_controller.rb [hunk 1]
```diff
@@ -2,4 +2,10 @@
 
 class AdvancedController < BlacklightAdvancedSearch::AdvancedController
   copy_blacklight_config_from(CatalogController)
+
+  def index
+    redirect_to '/catalog', params if params[:id]
+
```
Comment (christinach) [inline app/controllers/advanced_controller.rb]: @jrgriffiniii do you think the redirect should be '/' ?

File: spec/requests/advanced_search_spec.rb [hunk 2]
```diff
@@ -0,0 +1,15 @@
+# frozen_string_literal: true
+
+require 'rails_helper'
+
+describe 'Orangelight advanced search', type: :request do
+  it 'redirects search requests to the catalog search' do
+    get '/advanced?f[subject_facet][]=United+Nations-Decision+making&id=3681146&page=1&per_page=20'
+    expect(response.status).to eq(302)
+    expect(response).to redirect_to('/catalog')
```
Comment (christinach) [inline spec/requests/advanced_search_spec.rb]: and in the test as well '/' ?
