### PR TITLE
WIP - Your Account Revisions.  

### LINKED ISSUE #364: Handle and Log Exceptions when Account Related External Requests Fail
When requests back to bibdata's patron service or Voyager's web services fail these exceptions should be cleanly handled and logged.

### LINKED ISSUE #368: Fines Don't Map Correctly
Doublecheck the xpath statements used to pull fines from Voyager my account. They are incorrect right now. Pull live example from Voyager.

### PR DESCRIPTION
**Pull request by kevinreiss**
Make logging for bibdata patron requests and Voyager cleaner. Closes #364.

Handle failed connections to Bibdata/Voyager for Account Info."

Revise account templates, closes #368, #369, #370.

Scaffold out Means to Cancel Request/Renew Charged Items via Voyager APIs. Still a WIP.

### CODE REVIEW

**Comment by jpstroop** [comment]
6.7% seems like a lot for the coverage to drop. Is there anything that can be mocked? I had a conversation w/ @tpendragon and @escowles about how we might better test against Voyager last week. I forget if we came up with any ideas.

**Comment by escowles** [comment]
I don't think we got much further than "there must be some way to mock out the database somehow"

**Comment by escowles** [comment]
Though the biggest culprit looks like it focuses on the web api, which could be mocked or recorded using VCR: https://coveralls.io/builds/5042174/source?filename=lib%2Forangelight%2Fvoyager_client.rb

**Comment by kevinreiss** [comment]
I should have marked this WIP. Not finished yet. Setting up the mocks is
tedious and I haven't gotten to it yet. The APIs all involve some measure
of personal data so I've been mocking them with fake data using Faraday
stubs.

**Comment by kevinreiss** [comment]
Still a WIP but rebased and rubygems have come back to life.

**Comment by kevinreiss** [comment]
@tampakis @jpstroop After a long hiatus I've rebooted myself on this one. I will increase test coverage for the various interactions with Voyager Web Services and rebase this PR for final review.

**Comment by kevinreiss** [comment]
Pushing up for coveralls report.

**Comment by kevinreiss** [comment]
Still working on tests for various operations that need to run through Voyager web services. Don't merge yet.

**Comment by kevinreiss** [comment]
Checking coveralls coverage. Still have a lot of tests marked pending.

File: app/controllers/account_controller.rb [hunk 1]
```diff
@@ -14,22 +16,130 @@ def index
...
+    if voyager_account.status == 403
+      logger.info("403 Not Authorized to Connect to Voyager My Account Service.")
+      return false
+    end
+    if voyager_account.status == 404
+      logger.info("404 Patron id #{patron[:patron_id]} cannot be found in the Voyager My Account Service.")
+      return false 
+    end
+    account = VoyagerAccount.new(voyager_account.body)
+    #logger.info("#{account.source_doc}")
```
Comment (tampakis) [inline app/controllers/account_controller.rb]: remove commented line

File: Gemfile [hunk 2]
```diff
@@ -67,6 +68,9 @@ gem 'coveralls', require: false
 
 gem 'newrelic_rpm'
 
+#gem 'requests', :path => "/Users/kevinreiss/Projects/blacklight/requests/"
```
Comment (tampakis) [inline Gemfile]: remove

File: app/helpers/account_helper.rb [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+  ## FIXME - Move to 
+  ### Setup item status
+  ITEM_STATUS = YAML.load_file("#{Rails.root}/config/voyager_item_status.yml") rescue {}
+
+  def item_status_to_label item
+    ITEM_STATUS[item['statusCode'].to_i]
+  end
+
+  def format_date raw_date
+    raw_date.to_time.in_time_zone.strftime('%B %e %Y at %l:%M %p')
```
Comment (tampakis) [inline app/helpers/account_helper.rb]: I'm not sure we need to display time.

File: app/helpers/account_helper.rb [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+  def format_renew_string item
+    "#{item['itemId']}"
+  end
+
+  def display_account_balance fine_fee
+    "#{fine_fee['balanceTotal']}".strip.gsub(/\n\s+/, ' ')
+  end
+
+  def message_status item
+    unless item[:messages].nil?
```
Comment (tampakis) [inline app/helpers/account_helper.rb]: unless, else is bad style - do `if !item[:messages].nil?` instead if there's going to be an else clause

File: app/helpers/account_helper.rb [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+      content_tag(:span, "#{item[:messages]["message"]}", class: "message")
+    else
+      ""
+    end
+  end
+
+  def renew_status item
+    unless item[:renew_status].nil?
```
Comment (tampakis) [inline app/helpers/account_helper.rb]: if instead of unless

File: app/views/_account.html.erb [hunk 6]
```diff
@@ -7,20 +7,20 @@
       </button>
       <ul class="dropdown-menu" role="menu">
         <li>
-          <%= link_to 'My Account', page_path('account') %>
+          <%= link_to 'Your Account', main_app.page_path('account') %>
```
Comment (tampakis) [inline app/views/_account.html.erb]: Set up the "Your account" label in the locale yaml to DRY it up. Probably a separate configuration than the 'blacklight.header_links.logout' one.

File: app/views/devise/sessions/new.html.erb [hunk 7]
```diff
@@ -1,5 +1,5 @@
 <div class="col-md-12">
-  <h2 class="page-heading my-account">My Account</h2>
+  <h2 class="page-heading my-account">Your Account</h2>
```
Comment (tampakis) [inline app/views/devise/sessions/new.html.erb]: use locale yaml

File: app/views/pages/myaccount.html.erb [hunk 8]
```diff
@@ -1,5 +1,5 @@
 <div class="col-md-12">
-  <h1 class="page-heading">My Account</h1>
+  <h1 class="page-heading">Your Account</h1>
```
Comment (tampakis) [inline app/views/pages/myaccount.html.erb]: locale yaml

File: app/views/account/_charged_items.html.erb [hunk 9]
```diff
@@ -1,43 +1,61 @@
...
+                  <% if item["renewable"] == 'true' %>
+                    <label><input id="charged-<%= item["itemId"] %>" 
+                      type="checkbox" name="renew_items[]" 
+                      value="<%= format_renew_string(item) %>"> 
+                      Renew</label>
+                  <% else %>
+                    <span>Not renewable</span>
+                  <% end %>
+                <% else %>
+                  <span>Resolve Block to Renew</span>
```
Comment (tampakis) [inline app/views/account/_charged_items.html.erb]: Consistent casing. "Resolve block to renew"

File: app/views/account/_fines_fees.html.erb [hunk 10]
```diff
@@ -1,19 +1,33 @@
 <h2 class="section-heading">Fines and Fees</h2>
 <% if (!@account.fines_fees.nil?) %>
   <div class="table-responsive">
-    <table class="table table-striped table-bordered">
+    <table class="table table-striped table-bordered account--fines">
+      <thead>
+        <tr>
+          <td>Date</td>
+          <td>Title</td>
+          <td>Fee /Posting Type</td>
```
Comment (tampakis) [inline app/views/account/_fines_fees.html.erb]: Space on both sides of slash or none at all

File: config/requests.yml.tmpl [hunk 11]
```diff
@@ -6,6 +6,8 @@ defaults: &defaults
   proxy_base: http://library.princeton.edu/resolve/lookup?url=
   stackmap_base: https://library.princeton.edu/utils/map
   voyager_api_base: http://catalog.princeton.edu:7014
+  voyager_ub_id: 1@DB1
+  pulsearch_base: https://pulsearch.princeton.edu
```
Comment (tampakis) [inline config/requests.yml.tmpl]: Is this really needed? I feel like the rails url/route helpers should be sufficient.

File: lib/orangelight/voyager_patron_client.rb [hunk 12]
```diff
@@ -0,0 +1,206 @@
+require 'faraday'
+require 'faraday-cookie_jar'
+
+class VoyagerPatronClient
+
+  def initialize(patron)
+    @barcode = patron['barcode']
+    @last_name = patron['last_name']
+    @patron_id = patron['patron_id']
+    @ub_id = "1@PRINCETONDB20050302104001" #patron['ub_id'] is this global for all patrons?
```
Comment (tampakis) [inline lib/orangelight/voyager_patron_client.rb]: put this in the requests.yml? How important is this parameter anyway? I think I've put random values in it before and still gotten the desired response.

File: app/helpers/account_helper.rb (hunk 3 above)
Comment (kevinreiss) [inline app/helpers/account_helper.rb]: Joan requested this.

File: lib/orangelight/voyager_patron_client.rb (hunk 12 above)
Comment (kevinreiss) [inline lib/orangelight/voyager_patron_client.rb]: I've never been able to identify whether or not it is important.

File: config/requests.yml.tmpl (hunk 11 above)
Comment (kevinreiss) [inline config/requests.yml.tmpl]: This config value is their for the benefit of the requests engine. If the engine was mounted in an application other than OL and wanted to query the OL API it would need to know the base URL for OL.

Comment (kevinreiss) [inline config/requests.yml.tmpl]: I dumped in favor of using the solr doc output directly from bibdata.

File: config/locales/blacklight.en.yml [hunk 13]
```diff
@@ -4,6 +4,22 @@ en:
...
     voyager: 'Main Catalog'
     umlaut: 'Findit @ Princeton'
+    account:
+      inaccessible: 'Your Library Account is not available'
+      no_requests: 'You have no outstanding Requests'
+      no_pickup_items: 'You have no items available for Pickup.'
+      no_fines_fees: 'No outstanding fines or fees.'
+      no_blocks: 'No current blocks on your account.'
+      renew_label: 'Renew'
+      overdue_block: 'You have overdue recalled items. Please return this material Immediately.'
```
Comment (tampakis) [inline config/locales/blacklight.en.yml]: lower case "immediately"

File: config/locales/blacklight.en.yml [hunk 14]
```diff
@@ -4,6 +4,22 @@ en:
     welcome: 'Welcome!'
     voyager: 'Main Catalog'
     umlaut: 'Findit @ Princeton'
+    account:
+      inaccessible: 'Your Library Account is not available'
+      no_requests: 'You have no outstanding Requests'
+      no_pickup_items: 'You have no items available for Pickup.'
```
Comment (tampakis) [inline config/locales/blacklight.en.yml]: "pickup"

File: config/locales/blacklight.en.yml [hunk 15]
```diff
@@ -4,6 +4,22 @@ en:
     welcome: 'Welcome!'
     voyager: 'Main Catalog'
     umlaut: 'Findit @ Princeton'
+    account:
+      inaccessible: 'Your Library Account is not available'
+      no_requests: 'You have no outstanding Requests'
```
Comment (tampakis) [inline config/locales/blacklight.en.yml]: "requests"

File: config/locales/blacklight.en.yml [hunk 16]
```diff
@@ -4,6 +4,22 @@ en:
     welcome: 'Welcome!'
     voyager: 'Main Catalog'
     umlaut: 'Findit @ Princeton'
+    account:
+      inaccessible: 'Your Library Account is not available'
```
Comment (tampakis) [inline config/locales/blacklight.en.yml]: "library account"

File: spec/views/account/account_spec.rb [hunk 17]
```diff
@@ -49,16 +49,313 @@
...
+      expect(page).to have_content I18n.t('blacklight.account.no_fines_fees')
     end
 
     it "Display active requests" do
       expect(page).to have_content 'Pickup Location'
     end
 
     it "Displays items for pickup" do
-      expect(page).to have_content 'No items available for pickup'
+      expect(page).to have_content 'Items Available for Pickup'
```
Comment (tampakis) [inline spec/views/account/account_spec.rb]: I think this is true even if no items are available. Line 71 has us covered though. Can you add a spec for that tests whether `I18n.t('blacklight.account.no_pickup_items')` gets rendered when no items are available for pickup?

File: app/views/devise/sessions/new.html.erb [hunk 18]
```diff
@@ -1,5 +1,5 @@
 <div class="col-md-12">
-  <h2 class="page-heading my-account">My Account</h2>
+  <h2 class="page-heading my-account"></h2>
```
Comment (tampakis) [inline app/views/devise/sessions/new.html.erb]: There's no header here now.

**Comment by tampakis** [comment]
Ready to go
