### PR TITLE
Gaurd against invalid field list values

### LINKED ISSUE #1422: Invalid field list values raise exceptions in advanced search
## Backtrace

    line 196 of [PROJECT_ROOT]/app/helpers/advanced_helper.rb: block in process_query
    line 188 of [PROJECT_ROOT]/app/helpers/advanced_helper.rb: each
    line 188 of [PROJECT_ROOT]/app/helpers/advanced_helper.rb: process_query

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/39857149)

```
NoMethodError: undefined method `[]' for nil:NilClass
 advanced_helper.rb  196 block in process_query(...)
[PROJECT_ROOT]/app/helpers/advanced_helper.rb:196:in `block in process_query'
194           next
195         end
196         local_param = local_param_hash(field, config)
197 
198         queries << parsed.to_query(local_param)
```

### PR DESCRIPTION
**Pull request by eliotjordan**
Addresses https://app.honeybadger.io/projects/54399/faults/39857149
Closes #1422

### CODE REVIEW

**Comment by eliotjordan** [comment]
@tampakis I'm reasonably sure this doesn't break anything, but because the advanced search helper is so complex, it would great if you give this a look.

File: app/helpers/advanced_helper.rb [hunk 1]
```diff
@@ -220,30 +223,36 @@ module RenderConstraintsOverride
     def guided_search(my_params = params)
       constraints = []
       if my_params[:q1].present?
```
Comment (tampakis) [inline app/helpers/advanced_helper.rb]: could you add a check for f1 here too?

**Comment by eliotjordan** [comment]
@tampakis Updated
