### PR TITLE
Removes selected value in chosen select-advanced search form

### LINKED ISSUE #1267: Removing Formats in Advanced Search > Edit doesn't work
Steps to reproduce:
1. perform an advanced search with a format
2. click "Edit search"
3. remove the format
4. click "Search"
5. the format limit is still present

### PR DESCRIPTION
**Pull request by christinach**
closes #1267

### CODE REVIEW

File: app/assets/javascripts/orangelight.js [hunk 1]
```diff
@@ -18,12 +18,12 @@ $(document).ready(function() {
         container: "body",
         trigger: "hover"
     });
-
+
```
Comment (tampakis) [inline app/assets/javascripts/orangelight.js]: remove this indent

File: app/assets/javascripts/orangelight.js [hunk 2]
```diff
@@ -18,12 +18,12 @@ $(document).ready(function() {
...
         trigger: "hover"
     });
-
+     
     $('.chosen-select').chosen({
         allow_single_deselect: true,
         no_results_text: 'No results matched'
     });
-
+
```
Comment (tampakis) [inline app/assets/javascripts/orangelight.js]: Remove

File: spec/features/searching_spec.rb [hunk 3]
```diff
@@ -28,4 +28,17 @@
       expect(page).to have_selector '.icon-request-reading-room[aria-hidden="true"]'
     end
   end
+
+  context 'chosen selected values' do
+    it 'removes a chosen selected value' do
+      visit '/catalog?utf8=%E2%9C%93&f1=all_fields&q3=&f_inclusive%5Bformat%5D%5B%5D=Journal&search_field=advanced&commit=Search'
+      expect(page).to have_link 'Edit search'
+      page.find(:xpath, '//*[@id="editSearchLink"]').click
+      puts current_url
```
Comment (tampakis) [inline spec/features/searching_spec.rb]: remove the puts
