### PR TITLE
Handles bad session

### LINKED ISSUE #2635: Error with nil UID
NoMethodError: undefined method `empty?' for nil:NilClass

## Backtrace

    line 77 of [PROJECT_ROOT]/app/controllers/users/omniauth_callbacks_controller.rb: barcode_token_in_request_params
    line 38 of [PROJECT_ROOT]/app/controllers/users/omniauth_callbacks_controller.rb: barcode_user
    line 42 of [PROJECT_ROOT]/app/controllers/users/omniauth_callbacks_controller.rb: patron

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/80779922)

Visiting URL  https://catalog.princeton.edu/users/auth/barcode/callback (with a bad/empty session?) causes the error.

### PR DESCRIPTION
**Pull request by hectorcorrea**
This PR handles the bad session so that now instead of crashing and showing an HTTP 500 

http_500

we handle the error and that results in the (expected?) workflow to take place: redirect the user and show a flash warning indicating that the session in invalid.

redirect_flash

Fixes #2635

### CODE REVIEW

File: spec/controllers/omniauth_callbacks_controller_spec.rb [hunk 1]
```diff
@@ -26,6 +26,21 @@
...
 
+  describe 'bad omniauth session' do
+    let(:omniauth_response_nil_uid) do
+      OmniAuth::AuthHash.new(provider: 'barcode', uid: nil, info: { last_name: "" })
+    end
+    before do
+      controller.request.env['omniauth.auth'] = omniauth_response_nil_uid
+    end
+    it 'handles nil UID' do
+      allow(User).to receive(:from_barcode) { valid_barcode_user }
```
Comment (christinach) [inline spec/controllers/omniauth_callbacks_controller_spec.rb:37]: If the message is '...could not authenticate because barcode or last name did not match active patron..', can we use an invalid_barcode_user in the test?

Comment (hectorcorrea) [reply spec/controllers/omniauth_callbacks_controller_spec.rb:37]: The user itself is irrelevant for this test, what causes the error is the `nil` UID in the OmniAuth session.

**Review by christinach — APPROVED** [review]
