### PR TITLE
i3428: Update expected language in specs, remove pending

### LINKED ISSUE #3428: Stackmap specs are failing
See https://app.circleci.com/pipelines/github/pulibrary/orangelight/3408/workflows/ac3be612-3726-4777-af3b-c71ec95932ba/jobs/9039 for an example failure.

### PR DESCRIPTION
**Pull request by sandbergja**
closes #3428

### CODE REVIEW

File: spec/system/stackmap_spec.rb [hunk 1]
```diff
@@ -12,19 +12,15 @@
     end
 
     it 'has a link to the stackmap on the record page' do
-      pending('Vendor fixing Stackmap javascript')
       visit '/catalog/99125428126306421'
-      expect(page).to have_button('Map it', wait: 5)
-      click_button 'Map it'
+      expect(page).to have_button('Where to find it', wait: 5)
+      click_button 'Where to find it'
```
Comment (christinach) [inline spec/system/stackmap_spec.rb:17]: @sandbergja if you remove line 16 , will click_button wait by default? I would think it will wait if it is a button selector.

Comment (maxkadel) [reply spec/system/stackmap_spec.rb:17]: I think it will wait until the default Capybara wait time, which I think is less than 5 seconds

Comment (sandbergja) [reply spec/system/stackmap_spec.rb:17]: It's passing locally without line 16.  I vaguely remember some issue where it failed on CI though?  Pushing a separate branch without line 16 to check.

Comment (sandbergja) [reply spec/system/stackmap_spec.rb:16]: It worked!  So I removed that line.

**Review by kevinreiss — APPROVED** [review]
