### PR TITLE
Overriding Blacklight::Catalog#facet and handling cases where display information for a faceted field cannot be retrieved

### LINKED ISSUE #1338: [Orangelight/production] NoMethodError: undefined method `items' for nil:NilClass
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/36286262)

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #1338

### CODE REVIEW

File: app/controllers/catalog_controller.rb [hunk 1]
```diff
@@ -489,4 +489,23 @@ def index
   rescue ActionController::BadRequest
     render file: Rails.public_path.join('x400.html'), layout: true, status: :bad_request
   end
+
+  # @see Blacklight::Catalog#facet
```
Comment (hackmastera) [inline app/controllers/catalog_controller.rb]: can you add a github link to this comment? make sure to hit `y` to get the canonical link location, since it's a bit different in master. it might be worth noting that this changes with blacklight version 7.
