### PR TITLE
i3684: fix browse sorting for ayn character

### LINKED ISSUE #3864: Browse for the "ayn" character is off
### Expected behavior
Browse indexes should work consistently for the "ayn" character. 

### Actual behavior
Reported by [Joyce Bell](https://pulibrary.slack.com/archives/CA0UY0Q07/p1700144259062799) - "The indexing around the "ayn" character has been off for over a month. If I do a browse search for "ibn al-arabi" vs. "ibn al-ʻarabī" I get to different spots in the index. Same with "ibn ʻAbd al-ʻAzīz" vs. "ibn Abd al-Azīz"."

### Steps to replicate
Run a browse search for the examples from Joyce's report. 

https://catalog.princeton.edu/browse/subjects?search_field=browse_subject&q=ibn+al-arabi
https://catalog.princeton.edu/browse/subjects?search_field=browse_subject&q=ibn+al-%CA%BBarab%C4%AB

https://catalog.princeton.edu/browse/subjects?search_field=browse_subject&q=ibn+%CA%BBAbd+al-%CA%BBAz%C4%ABz
https://catalog.princeton.edu/browse/subjects?search_field=browse_subject&q=ibn+Abd+al-Az%C4%ABz

Both of the above pairs should take you to the same place in the subject browse index. 

### Impact of this bug
No real workaround. 

### Implementation notes, if any
We confirmed browse index cron jobs are running successfully on their schedule.

### PR DESCRIPTION
**Pull request by sandbergja**
closes #3864 

I've run the author browse list in staging with this PR.

### CODE REVIEW

File: lib/orangelight/browse_lists.rb [hunk 1]
```diff
@@ -17,7 +17,7 @@ def connection
       dbuser = config['username']
       dbname = config['database']
       password = config['password']
-      port = config['port']
+      port = config['port'] || 5432
```
Comment (sandbergja) [inline lib/orangelight/browse_lists.rb:20]: This change was needed to get the rake task to run in circleci.

**Review by christinach — APPROVED** [review]
Thanks @sandbergja !
