### PR TITLE
Various Account Page Fixes

### LINKED ISSUE #456: BorrowDirect requests display item titles in all caps and pickup locations start with a period
screen shot 2016-04-26 at 10 40 53 am

### LINKED ISSUE #467: Update Renewal Top Level Message with Success/Failure
Renewal requests response contain a somewhat cryptic top-level response that reflects failed renewals within the entire request, see https://github.com/pulibrary/orangelight/blob/development/spec/fixtures/voyager_account_with_recal_and_fines_renew_response.xml#L67. The general flash message should indicate the failure in some fashion.

### LINKED ISSUE #476: Remove Item Type Column in Charted Items on Account Page
From Joan: In “charged items”, remove the “item type” column entirely.  It’s not helpful to patrons.

### LINKED ISSUE #477: Recall Display in Charged Items
From Joan: "In “charged items” and then within the “status” column, change “recall request” to “recalled”.  The item has been recalled and the patron needs to more clearly understand that. - I think we display whatever string Voyager sends back here. We'd need to write a helper to munge that and alter the language for items that have been recalled.

### PR DESCRIPTION
**Pull request by kevinreiss**
Change per Joan. Closes #477.
Remove item type column. Closes #476.
Display call number as 'Borrow Direct' for charged BD items. Closes #456.
Add partial renewal fail message to flash reponse. Closes #467.

### CODE REVIEW

File: app/controllers/account_controller.rb [hunk 1]
```diff
@@ -23,7 +23,11 @@ def renew
       if params[:renew_items].nil?
         format.js { flash.now[:notice] =  I18n.t('blacklight.account.renew_no_items') }
       elsif !@account.nil?
-        format.js { flash.now[:notice] =  I18n.t('blacklight.account.renew_success') }
+        if @account.failed_renewals?
+          format.js { flash.now[:notice] =  I18n.t('blacklight.account.renew_partial_fail') }
```
Comment (tampakis) [inline app/controllers/account_controller.rb]: can you make this a flash warning rather than notice?
